### ISSUE TITLE
Rare Gumtromp Missing?

### ISSUE THREAD

**Issue by JoshTNT** [TheLocalMoon/TLLPSData#2]
On Candy Island, in the Rare Monster Market. Rare Kayna and Noggin are there but Rare Gumtromp isn't
![image_2023-12-27_125544493](https://github.com/TheLocalMoon/TLLPSData/assets/154987303/06423e4b-e60a-4a40-a277-03ec828391f4)

**Comment by TheLocalMoon** [comment]
i go fix!1!
